# Generated by Django 3.2.9 on 2021-11-24 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_login_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login_field',
        ),
    ]
