# Generated by Django 3.2.9 on 2021-11-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login',
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(default='Empty', to='app.Tag', verbose_name='Тег'),
        ),
    ]
