# Generated by Django 3.2.9 on 2021-11-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211124_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='app.Tag', verbose_name='Тег'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(default='Empty', max_length=150, verbose_name='Теги'),
        ),
    ]
