# Generated by Django 3.2.9 on 2021-11-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_tag_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnsuccessfulTries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('tries', models.IntegerField(null=True)),
            ],
        ),
    ]
