# Generated by Django 3.2.9 on 2021-12-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('AE', 'Юр. лицо'), ('AI', 'Физ. лицо')], default='AE', max_length=3, verbose_name='Тип пользователя'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(blank=True, upload_to='image/', verbose_name='Изображение'),
        ),
    ]
