# Generated by Django 3.2.9 on 2021-12-06 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20211206_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityPerson',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.user')),
                ('short_name', models.CharField(max_length=255, verbose_name='Сокращенное название')),
                ('full_name', models.CharField(max_length=512, verbose_name='Полное название')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalPerson',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.user')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('patronymic', models.CharField(max_length=64)),
                ('passport', models.CharField(blank=True, max_length=11, null=True, verbose_name='Паспорт - серия, номер')),
                ('passport_issued_by', models.CharField(blank=True, max_length=250, null=True, verbose_name='Кем выдан')),
                ('registration_address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес регистрации, индекс')),
                ('residence_address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Фактический адрес проживания, индекс')),
                ('snils', models.CharField(max_length=14, verbose_name='СНИЛС')),
            ],
        ),
    ]
